[package]
name = "rush"
version = "0.1.0"
authors = ["Skye Bleed <monarrk@aaathats3as.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.0"
